[package]
name = "harbor-ports-cli"
version = "1.0.0"
edition = "2024"
description = "A minimalist and fast port managment CLI"
license = "MIT"
repository = "https://github.com/RedJulu/harbor-ports-cli"
readme = "README.md"

[[bin]]
name = "harbor"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
colored = "3.1.1"
comfy-table = "8.0.1"
libc = "0.2.189"
listeners = "0.6.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
